### ISSUE TITLE
Transforms for all build configurations are run when building a project using a particular configuration

### ISSUE THREAD

**Issue by pmarflee** [cezarypiatek/VanillaTransformer#1]
First of all, thanks for creating VanillaTransformer.  I am using it with a WinForms application to copy customer-specific application settings into the build output when selecting the build configuration for a particular customer.

One thing that puzzled me however, is why all transformations are run when building a project.  For instance, if I have build configurations named *CustomerX*, *CustomerY*, and *CustomerZ*, why are the transformations for all these configurations run when I build against configuration *CustomerX*?  The result of this is that the generated config for each build configuration has to be given a different name.  But I want the generated file to have the name *appsettings.config*, because this is the name of the file referenced from my application's *app.config*.  At the moment, I have an MSBuild **Copy** task to rename the required file and copy it into the build output:

`<Copy SourceFiles="TransformedConfigs\appsettings.$(Configuration).config" DestinationFiles="$(OutputPath)\appsettings.config" />`

Is the action of running all transforms by design?  It seems like you'd only want to run transforms for the chosen build configuration.

**Comment by cezarypiatek** [comment]
Hi
Thank for your feedback.
As you assumed, this behavior is by design. The main idea was to create transformations per environment not per compilation. I've been thinking about introducing some kind of conditions for entries in transformations.config but I want to keep this tool simple (I can't use msbuild condition mechanism, because the parser is a private class of msbuild library). However, I think you can solve you problem by redirecting transformation results into appropriate directories (As I know, msbuild put binaries per compilation in separate subdirectory inside the bin directory). Your transformations.config might looks like:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<root> 
  <transformationGroup pattern="appsettings.pattern.config">
    <transformation values="appsettings.CustomerX.config" output="bin\CustomerX\AppName.config" />    
    <transformation values="appsettings.CustomerY.config" output="bin\CustomerY\AppName.config" />
  </transformationGroup>
</root>
```

Please let me know if that solves your problem.

**Comment by pmarflee** [comment]
Thanks for your reply. In the end I decided to stick with my original approach, as I needed to finish the project and begin other work. If I use VanillaTransformer again I will consider doing things a different way.
