### ISSUE TITLE
Add support for .net core

### ISSUE THREAD

**Issue by cezarypiatek** [cezarypiatek/VanillaTransformer#8]
A nuget package should contain MsBuildTask for `MSBuild.exe` and ‘dotnet msbuild’

A detailed instruction can be found here:

https://natemcmaster.com/blog/2017/07/05/msbuild-task-in-nuget/
https://github.com/natemcmaster/msbuild-tasks

**Comment by izaruba** [comment]
Looks like there will be a problem since the logic is split by two DLLs.
As described in [Nate's next article](https://natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/) a NuGet package containing a Task does not support any dependencies.

There are few options to handle the issue.
1. Combine `VanillaTransformer` and `VanillaTransformer.Core` into a single project.

2. Create command line tool ([.NET Core Global Tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create))
In that case the tool will be called from `.csproj` like
`<Exec Command="transform -?" />`
or that can be used as a `ToolTask` (a task wrapper above a command line tool).

which option will suit?

**Comment by cezarypiatek** [comment]
Hi @izaruba 

Thanks for investigating this issue. `VanillaTransformer` was recently split into two projects `VanillaTransformer` and `VanillaTransformer.Core` because I wanted to publish it also as a console app and I didn't want to duplicate the code.  Now I've got a new idea: how about converting `VanillaTransformer.Core` into `Shared Project` ? Thanks to that we can compile the shared code into `VanillaTransformer` as well as `VanillaTransformer.Console`.

![image](https://user-images.githubusercontent.com/7759991/46545989-2dab1000-c8c8-11e8-9478-0edf26469012.png)

Could you try to implement this solution?

**Comment by cezarypiatek** [comment]
I've created `develop` branch

**Comment by izaruba** [comment]
Created a PR to `develop` branch. Everything is in the `./DotNetCore` folder.
Waiting for your feedback if anything needs to be changed.
